title: Still Not a Quant Dev
description: Daily logs of learning quantitative development â€” publicly and imperfectly.
theme: minima

baseurl: "/still-not-a-quant-dev"
url: "https://arnavgupta3911.github.io"

header_pages:
  - about.md
  - posts.md
